trainer:
  gpus: [0]
  precision: 16
  max_steps: 40000
  check_val_every_n_epoch: 2

  callbacks:
    - class_path: project.callbacks.ConfusionMatrixCallback
      init_args:
        name: "conf_mat"
        modes: ["val", "test"]
        num_classes: 10
    - class_path: project.callbacks.ErrorAtUncertaintyCallback
      init_args:
        name: "uncert"
        modes: ["train", "val", "test"]
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image_worst"
        queue_size: 32
        modes: ["val", "test"]
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image_best"
        queue_size: 32
        modes: ["val", "test"]
        negate_priority: true
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image"
        queue_size: 32
        modes: ["train"]
        flush_interval: 1000
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: "val/cifar10/accuracy"
        mode: "max"

optimizer:
  class_path: torch.optim.AdamW
  init_args: 
    lr: 0.001
    weight_decay: 0.0001

lr_scheduler_interval: 'step'
lr_scheduler:
  class_path: torch.optim.lr_scheduler.OneCycleLR
  init_args: 
    max_lr: 0.001
    # TODO find a way to link to trainer.max_steps
    total_steps: 40000
    pct_start: 0.3
    div_factor: 4
    final_div_factor: 20
