trainer:
  gpus: 2
  precision: 16
  max_steps: 100000
  check_val_every_n_epoch: 2
  strategy: "ddp"
  gradient_clip_val: 5.0

  callbacks:
    - class_path: project.callbacks.ConfusionMatrixCallback
      init_args:
        name: "conf_mat"
        modes: ["val", "test"]
        num_classes: 10
    - class_path: project.callbacks.ErrorAtUncertaintyCallback
      init_args:
        name: "uncert"
        modes: ["train", "val", "test"]
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image_worst"
        queue_size: 32
        modes: ["val", "test"]
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image_best"
        queue_size: 32
        modes: ["val", "test"]
        negate_priority: true
    - class_path: project.callbacks.ImageLoggingCallback
      init_args:
        name: "image"
        queue_size: 32
        modes: ["train"]
        flush_interval: 1000
    - class_path: project.callbacks.MaskedImageLoggingCallback
      init_args:
        name: "masked_img"
        queue_size: 32
        modes: ["train"]
        flush_interval: 1000
    - class_path: project.callbacks.FilledImageLoggingCallback
      init_args:
        name: "filled_img"
        queue_size: 32
        modes: ["train"]
        flush_interval: 1000

    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      #- class_path: pytorch_lightning.callbacks.EarlyStopping
      #  init_args:
      #    patience: 10
      #    monitor: "val/cifar10/accuracy"
      #    mode: "max"

data:
  class_path: pl_bolts.datamodules.CIFAR10DataModule
  init_args:
    data_dir: "./data"
    num_workers: 16
    batch_size: 64


model:
  class_path: project.model.ViTModel
    

optimizer:
  class_path: torch.optim.AdamW
  init_args: 
    lr: 0.0001
    weight_decay: 0.01

lr_scheduler_interval: 'step'
lr_scheduler:
  class_path: torch.optim.lr_scheduler.OneCycleLR
  init_args: 
    max_lr: 0.0001
    # TODO find a way to link to trainer.max_steps
    total_steps: 40000
    pct_start: 0.3
    div_factor: 1
    final_div_factor: 20
