version: 2.1


orbs:
  codecov: codecov/codecov@1.0.2

commands:
  setup_node_modules:
    steps:
      - run: sudo apt update
      - run: sudo apt install -y npm
      - run: sudo npm cache clean -f
      - run: sudo npm install -g n
      - run: sudo n stable
      - run:
          name: Install static type checker
          command: npm ci



jobs:
    check_code_quality:
        docker:
            - image: circleci/python:3.10
        steps:
            - checkout
            - run: 
                name: Run quality tests
                command: make quality

    run_tests:
        docker:
            - image: circleci/python:3.10
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: make init
            - save_cache:
                paths:
                  - ~/.cache/pip
                key: v1-dependencies-{{ checksum "setup.py" }}
            - run: 
                name: Run tests
                command: make test-ci
            - setup_node_modules
            - run: 
                name: Run static type checking
                command: make types
            - codecov/upload:
                file: coverage.xml


workflow_filters: &workflow_filters
    filters:
        branches:
            only:
                - master
                - feat/circleci


workflows:
    version: 2
    build_and_test:
        jobs:
            - check_code_quality
            - run_tests
