# @package _group_
num_workers: 4
batch_size: 8

train:
  _target_: torchvision.datasets.FakeData
  params:
    size: 10000
    image_size: [1, 128, 128]
    transform:
      _target_: torchvision.transforms.ToTensor

validate:
  _target_: torchvision.datasets.FakeData
  params:
    size: 100
    image_size: [1, 128, 128]
    transform:
      _target_: torchvision.transforms.ToTensor

test:
  _target_: torchvision.datasets.FakeData
  params:
    size: 100
    image_size: [1, 128, 128]
    transform:
      _target_: torchvision.transforms.ToTensor

# optionally, as split from training set
# validate: 100
# test: 100
