# @package _group_
_target_: pytorch_lightning.Trainer

# Uncomment and set checkpoint path for inference only
#test_only: true
#load_from_checkpoint: /mnt/iscsi/sr-mb/output/hrnet.ckpt

# Use any pytorch_lightning.Trainer param 
# https://pytorch-lightning.readthedocs.io/en/stable/trainer.html#trainer-flags
params:
  max_epochs: 1

  # GPU / mixed precision config
  # Turing or newer GPU required for mixed precision to work
  #gpus: 1
  amp_level: O1
  #precision: 16 # change this if GPU doesn't support 16 bit float
  
  #train_percent_check: 0.1
  check_val_every_n_epoch: 2
  
  # Change this to path where outputs will be written
  # NOTE: this should be an absolute path or unwanted subdirs will be created
  default_root_dir: ${oc.env:OUTPUT_PATH}

  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: ${trainer.params.default_root_dir}
      name: ${now:%Y-%m-%d}
      version: ${now:%H-%M-%S}

  # Callbacks leveraging combustion's visualization
  #callbacks:
  #  - _target_: combustion.lightning.callbacks.BlendVisualizeCallback
  #    params: 
  #      name: 'detect_true'
  #      triggers: ['train']
  #      attr_name: "last_img"
  #      interval: 1000
  #      colormap: [null, "gnuplot"]
  #      alpha: [1.0, 0.8]
